export const Images = {
    Home: require('../Assests/Image/home.png'),
    Figma1: require('../Assests/Image/figma1.png'),
    Figma2: require('../Assests/Image/figma2.png'),
    Figma3: require('../Assests/Image/figma3.png'),
    Camera: require('../Assests/Image/3rd.png'),
    Camerab: require('../Assests/Image/Ellipse.png'),
    Google: require('../Assests/Image/Google.png'),
    Login: require('../Assests/Image/Group3.png'),
    Sign: require('../Assests/Image/Group4.png'),
    Create: require('../Assests/Image/Group5.png'),
    Update: require('../Assests/Image/Groupf.png'),
    Telegram: require('../Assests/Image/Telegram.png'),
    Apple: require('../Assests/Image/Vector.png'),
    Whatsapp: require('../Assests/Image/Whatsapp.png'),
    Common:require('../Assests/Image/Upper.png'),
    Hembarg:require('../Assests/Image/Hembarg.png'),
    Hom:require('../Assests/Image/Hom.png'),
    Wallet:require('../Assests/Image/Wallet.png'),
    DashBoard:require('../Assests/Image/Chart.png'),
    Profile:require('../Assests/Image/Profile.png'),
    Back:require('../Assests/Image/BackArrow.png'),
    Greater:require('../Assests/Image/Arrow.png'),
    Recent:require('../Assests/Image/I1.png'),
    Payment:require('../Assests/Image/I2.png'),
    Customer:require('../Assests/Image/I3.png'),
    Logout:require('../Assests/Image/I4.png'),
    Eye:require('../Assests/Image/eye.jpeg'),
    CloseEye:require('../Assests/Image/closeeye.png'),
    Firoz:require('../Assests/Image/photo.png'),
    Social:require('../Assests/Image/Social.png'),
    Settings:require('../Assests/Image/Setting.png'),
    Plus:require('../Assests/Image/plus.png'),
    Add:require('../Assests/Image/add.png'),
    Whatsapp2:require('../Assests/Image/Whatsappverfiy.png'),
    DropDown:require('../Assests/Image/drop.png'),
    DoubleAr:require('../Assests/Image/Arrowd.png'),
    FirstE:require('../Assests/Image/Circle.png'),
    IND:require('../Assests/Image/India.png'),
    USA:require('../Assests/Image/Usa.png'),
    Photo1:require('../Assests/Image/photo1.png'),
    Photo2:require('../Assests/Image/photo2.png'),
    Photo3:require('../Assests/Image/photo3.png'),
    Photo4:require('../Assests/Image/photo4.png'),
    SubPlann:require('../Assests/Image/Subtraction.png'),
    DropIcon:require('../Assests/Image/drop1.png'),
    BackGround:require('../Assests/Image/background.png'),
    Send:require('../Assests/Image/send.png'),
    Matchback:require('../Assests/Image/Match.png'),
    Name:require('../Assests/Image/name.png'),
    Email:require('../Assests/Image/email.png'),
    Phone:require('../Assests/Image/phone.png'),
    Flag:require('../Assests/Image/flag.png'),
    Language:require('../Assests/Image/language.png'),
    UnCheck:require('../Assests/Image/uncheck.png'),
    CheckBtn:require('../Assests/Image/checked.png'),
    Profiles:require('../Assests/Image/profiles.png'),
}